notifications:
  email: false
sudo: required
services:
- docker
before_install:
- docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit
script:
- docker exec -it emscripten ./run.sh
